cdek:
  api:
    url: https://api.edu.cdek.ru/v2
    client-id: wqGwiQx0gg8mLtiEKsUinjVSICCjtTEP
    client-secret: RmAmgvSgSl1yirlz9QupbzOJVqhCxcP5
    from-city-code: 5444
    tariff-code: 136

yildam:
  pricing:
    base-price: 190.0
    max-base-weight: 6.0
    price-per-kg: 60.0

spring:
  application:
    name: Levantee
  datasource:
    url: jdbc:postgresql://localhost:5432/orderservice
    username: postgres
    password: qwerty
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect